services:
  app:
    image: 'jc21/nginx-proxy-manager:2'
    restart: unless-stopped
    ports:
      - ${UI_PORT}:81
      - ${HTTPS_PORT}:443
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    env_file: .env
    networks:
      - proxy_network

networks:
  proxy_network:
    external: true
