services:
  nextcloud:
    image: lscr.io/linuxserver/nextcloud:31.0.7
    container_name: nextcloud
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ./config:/config
      - ./data:/data
    restart: unless-stopped
    networks:
      - proxy_network

networks:
  proxy_network:
    external: true
